[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "smri-fm"
dynamic = ["version"]
description = "MedARC sMRI foundation model"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "antspyx",
    "braceexpand",
    "datasets",
    "einops",
    "huggingface-hub",
    "ipython",
    "jaxtyping",
    "jupyter",
    "matplotlib",
    "nibabel",
    "numpy",
    "omegaconf",
    "pandas",
    "pre-commit",
    "pytest",
    "pyyaml",
    "s3fs",
    "scikit-learn",
    "scipy",
    "seaborn",
    "tabulate",
    "templateflow",
    "timm",
    "torch==2.8.0",
    "torchvision",
    "tqdm",
    "wandb",
    "webdataset",
    "asparagus",
    "asparagus_preprocessing",
]

[tool.uv.sources]
asparagus = { path = "third_party/asparagus", editable = true }
asparagus_preprocessing = { path = "third_party/asparagus_preprocessing", editable = true }

[tool.uv]
override-dependencies = [
    "torch==2.8.0",
    "torchvision==0.23.0",
    "huggingface-hub<1.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/_version.py"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F722"]

[tool.pytest.ini_options]
norecursedirs = ["third_party", ".scratch"]
